Update

diff --git a/.github/workflows/unittests.yml b/.github/workflows/unittests.yml
--- a/.github/workflows/unittests.yml
+++ b/.github/workflows/unittests.yml
@@ -27,13 +27,16 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Format-python-scripts
+      - name: Run-unit-tests
         run: | 
-          sudo apt install -y black shfmt
-          black ./
-          shfmt -l -w ./
-      - name: Commit new documentation to branch
-        uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          commit_message: Python and bash scripts reformatted   
-          branch: main
+          sudo apt update -y 
+          sudo apt install -y python python3-pip
+          pip install matplotlib==3.8.0
+          pip install numpy==1.25.2
+          pip install scipy==1.9.3
+          python -m unittests
+          RESULT=$?
+          if [[ ${RESULT} -ne 0 ]]; then
+          printf "Tests failed to pass"
+          exit ${RESULT}
+          fi
